export const ACP_AGENTS_CONFIG = {
  atlas: {
    id: 'atlas',
    name: 'Atlas',
    title: 'Diagnóstico Comercial',
    category: 'estrategia',
    phase: 'Fase 1',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Conduz diagnóstico inicial, mapeia gargalos e gera plano 30-60-90.',
    icon: 'Search',
    color: '#2563eb',
    soft: '#eff6ff',
    placeholder: 'Nome da empresa, segmento, ticket médio, leads/mês, vendas/mês, CAC, LTV, canal principal, ferramentas, time comercial, principais queixas...'
  },
  hera: {
    id: 'hera',
    name: 'Hera',
    title: 'Construção de ICP',
    category: 'estrategia',
    phase: 'Fase 2',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Constrói ICP com 6 critérios baseado em dados reais da base histórica.',
    icon: 'Target',
    color: '#0891b2',
    soft: '#ecfeff',
    placeholder: 'Segmento da empresa, Top 20% clientes (perfil, LTV, retenção), padrões de quem comprou e não comprou, canais de aquisição...'
  },
  prometeu: {
    id: 'prometeu',
    name: 'Prometeu',
    title: 'Arquitetura de Oferta',
    category: 'estrategia',
    phase: 'Fase 3',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Estrutura a oferta com value stack e ancoragem de preço.',
    icon: 'Layout',
    color: '#7c3aed',
    soft: '#f5f3ff',
    placeholder: 'ICPs validados, catálogo de produtos/serviços, ticket atual e desejado, cases e provas, objeções comuns, concorrentes...'
  },
  mercurio: {
    id: 'mercurio',
    name: 'Mercúrio',
    title: 'Funil de Aquisição e Mídia',
    category: 'aquisicao',
    phase: 'Fase 4',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Opera campanhas de aquisição com filtro de qualidade e otimização contínua.',
    icon: 'Zap',
    color: '#ea580c',
    soft: '#fff7ed',
    placeholder: 'ICPs, oferta, verba disponível, meta de leads qualificados, CAC alvo, canais (Meta/Google/LinkedIn), criativos disponíveis...'
  },
  apolo: {
    id: 'apolo',
    name: 'Apolo',
    title: 'Funil de Autoridade e Conteúdo',
    category: 'autoridade',
    phase: 'Fase 5',
    autonomy: 1,
    autonomyLabel: 'Autônomo',
    description: 'Cria calendário PIES e banco de pautas para autoridade digital.',
    icon: 'Feather',
    color: '#059669',
    soft: '#ecfdf5',
    placeholder: 'ICPs, oferta, top objeções, tom de voz, canais ativos (Instagram/LinkedIn/Blog), nicho de mercado...'
  },
  iris: {
    id: 'iris',
    name: 'Iris',
    title: 'Mensagens e Criativos',
    category: 'aquisicao',
    phase: 'Fase 6',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Cria copies de anúncio e briefings que atraem o ICP e filtram curiosos.',
    icon: 'PenTool',
    color: '#db2777',
    soft: '#fdf2f8',
    placeholder: 'ICP, oferta, value stack, ângulos de venda, cases, tom de voz, formato desejado (imagem/vídeo/carrossel)...'
  },
  cadmo: {
    id: 'cadmo',
    name: 'Cadmo',
    title: 'Lead Scoring e Qualificação',
    category: 'operacao',
    phase: 'Fase 7',
    autonomy: 1,
    autonomyLabel: 'Autônomo',
    description: 'Atribui score 0-100 e classifica leads em Frio/Morno/Quente/Urgente.',
    icon: 'BarChart',
    color: '#dc2626',
    soft: '#fef2f2',
    placeholder: 'Dados do lead: nome, cargo, empresa, segmento, interações, origem, cargo de decisão, demonstrou dor, orçamento disponível...'
  },
  orfeu: {
    id: 'orfeu',
    name: 'Orfeu',
    title: 'Roteiros e Objeções',
    category: 'operacao',
    phase: 'Fase 8',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Cria roteiros por papel e documenta objeções com tratamento.',
    icon: 'MessageSquare',
    color: '#0d9488',
    soft: '#f0fdfa',
    placeholder: 'Papel (SDR/BDR/Closer), ICP, oferta, value stack, objeções mais comuns no segmento, perfil do lead...'
  },
  hermes: {
    id: 'hermes',
    name: 'Hermes',
    title: 'CRM e Higiene de Dados',
    category: 'operacao',
    phase: 'Fase 9',
    autonomy: 1,
    autonomyLabel: 'Autônomo',
    description: 'Configura pipeline, auditoria de higiene e alertas de duplicidade.',
    icon: 'Database',
    color: '#475569',
    soft: '#f8fafc',
    placeholder: 'CRM atual (qual plataforma), pipeline atual, campos existentes, volume de leads, principais problemas com dados...'
  },
  demeter: {
    id: 'demeter',
    name: 'Deméter',
    title: 'Nurture e Reativação',
    category: 'operacao',
    phase: 'Fase 10',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Cria sequência de 14 dias e reativa leads frios.',
    icon: 'Sprout',
    color: '#65a30d',
    soft: '#f7fee7',
    placeholder: 'Segmento/ICP do lead, conteúdos disponíveis, objeções comuns, canais de contato (email/WhatsApp), tempo de inatividade...'
  },
  cronos: {
    id: 'cronos',
    name: 'Cronos',
    title: 'KPI e Unit Economics',
    category: 'gestao',
    phase: 'Fase 11',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Calcula CAC, LTV, payback e margem com alertas de sanidade.',
    icon: 'TrendingUp',
    color: '#ca8a04',
    soft: '#fefce8',
    placeholder: 'Gasto total com marketing/vendas, leads gerados, clientes conquistados, receita por cliente, período (mês/trimestre), canais usados...'
  },
  atena: {
    id: 'atena',
    name: 'Atena',
    title: 'Inteligência Competitiva',
    category: 'estrategia',
    phase: 'Fase 12',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Mapeia concorrentes, identifica gaps e alimenta argumento comercial.',
    icon: 'Search',
    color: '#4f46e5',
    soft: '#eef2ff',
    placeholder: 'Segmento de mercado, principais concorrentes (nomes), sua oferta, ICP, histórico de perdas para concorrentes...'
  },
  hestia: {
    id: 'hestia',
    name: 'Héstia',
    title: 'Retenção e Sinais de Churn',
    category: 'operacao',
    phase: 'Fase 13',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Monitora 12 sinais de churn e classifica clientes em verde/amarelo/vermelho.',
    icon: 'Heart',
    color: '#be185d',
    soft: '#fdf2f8',
    placeholder: 'Dados do cliente: tempo de contrato, NPS, uso do produto, status de pagamento, interações recentes, tickets de suporte...'
  },
  zeus: {
    id: 'zeus',
    name: 'Zeus',
    title: 'Planejamento Trimestral',
    category: 'gestao',
    phase: 'Fase 14',
    autonomy: 2,
    autonomyLabel: 'Semi-Autônomo',
    description: 'Conduz planejamento trimestral com metas SMART e Top 5 prioridades.',
    icon: 'Calendar',
    color: '#1e40af',
    soft: '#eff6ff',
    placeholder: 'Trimestre a planejar (ex: 2026-Q3), resultados do trimestre anterior, metas desejadas, recursos disponíveis,时间 comercial...'
  }
};

export const ACP_CATEGORIES = [
  { id: 'todos', label: 'Todos', description: 'Visão geral dos 14 agentes ACP v2.0' },
  { id: 'estrategia', label: 'Estratégia', description: 'Diagnóstico, ICP, Oferta e Inteligência Competitiva' },
  { id: 'aquisicao', label: 'Aquisição', description: 'Mídia, Criativos e Funil de Aquisição' },
  { id: 'autoridade', label: 'Autoridade', description: 'Conteúdo Estratégico (Matriz PIES)' },
  { id: 'operacao', label: 'Operação', description: 'Scoring, Roteiros, CRM, Nurture, Retenção' },
  { id: 'gestao', label: 'Gestão', description: 'KPIs, Unit Economics e Planejamento Trimestral' }
];

export type AcpAgentId = keyof typeof ACP_AGENTS_CONFIG;
